### ISSUE TITLE
ModuleNotFoundError: No module named 'LiCSBAS_tools_lib'

### ISSUE THREAD

**Issue by suatcoskun** [yumorishita/LiCSBASpatch_AIST_ALOS#1]
My licsbas tool install and work correctly but when tried to start AIST ALOS i took this error message do you have any advice.

(licsbas) suat@suat:~/Downloads/611_0800_343/LiCSBASpatch_AIST_ALOS-main$ source /home/suat/Downloads/611_0800_343/LiCSBASpatch_AIST_ALOS-main/bashrc_LiCSBAS_ALOS.sh
(licsbas) suat@suat:~/Downloads/611_0800_343/LiCSBASpatch_AIST_ALOS-main$ ./batch_LiCSBAS_ALOS.sh

Start step: 01
End step:   16
Log file:   log/202209111759batch_LiCSBAS_ALOS_01_16.log

Traceback (most recent call last):
  File "/home/suat/Downloads/611_0800_343/LiCSBASpatch_AIST_ALOS-main/bin/LiCSBAS01_get_geotiff_ALOS.py", line 71, in <module>
    import LiCSBAS_tools_lib as tools_lib
ModuleNotFoundError: No module named 'LiCSBAS_tools_lib'
[202209111820batch_LiCSBAS_ALOS_01_16.log](https://github.com/yumorishita/LiCSBASpatch_AIST_ALOS/files/9542869/202209111820batch_LiCSBAS_ALOS_01_16.log)

.

**Comment by yumorishita** [comment]
Have you installed LiCSBAS (see [here](https://github.com/yumorishita/LiCSBASpatch_AIST_ALOS#installation))?

**Comment by suatcoskun** [comment]
> Have you installed LiCSBAS (see [here](https://github.com/yumorishita/LiCSBASpatch_AIST_ALOS#installation))?

Yes i have already install LICSBAS and its work properlly.

**Comment by yumorishita** [comment]
What is the output of `LiCSBAS_check_install.py`?

**Comment by suatcoskun** [comment]
> What is the stdout of `LiCSBAS_check_install.py`?

These are my results:

(licsbas) suat@suat:~/Downloads/043A_05221_121313/LiCSBAS-master$ LiCSBAS_check_install.py

Python version: 3.10.4
  OK

Check required modues and versions
  astropy(5.0.4) OK
  bs4(4.11.1) OK
  h5py(3.6.0) OK
  matplotlib(3.5.1) OK
  numpy(1.22.3) OK
  psutil(5.9.0) OK
  requests(2.28.0) OK
  statsmodels(0.13.2) OK
  gdal(3.4.1) OK

Check LiCSBAS commands
  OK

Check LiCSBAS library
  OK

LiCSBAS install is OK

**Comment by yumorishita** [comment]
Strange. I have no idea. Please try `./batch_LiCSBAS_ALOS.sh` again.

**Comment by suatcoskun** [comment]
WHEN İ USE 'bashrc_LiCSBAS_ALOS.sh'  İ took ModuleNotFoundError: No module named 'LiCSBAS_tools_lib' error. 
But if i use  bashrc_LiCSBAS.sh system is work. So that i modify bashrc_LiCSBAS_ALOS.sh like this;

Previous
## Path
export LICSBAS_ALOS_PATH="$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)"
export PATH="$LICSBAS_ALOS_PATH/bin:$PATH"

New one:
## Path
export LICSBAS_ALOS_PATH="$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)"
export PATH="$LICSBAS_ALOS_PATH/bin:$PATH"
export PYTHONPATH="$LICSBAS_ALOS_PATH/LiCSBAS_lib:$PYTHONPATH"


İs İt true?

Thank YOU...

**Comment by yumorishita** [comment]
It does not make sense because this module does not include LiCSBAS_lib.
Did you use the same terminal as the one you ran LiCSBAS?
What is the return of the following commands?
```
echo $PATH
echo $PYTHONPATH
```

**Comment by suatcoskun** [comment]
Yes i used the same terminal and these are my results.

![vel mskd](https://user-images.githubusercontent.com/36503613/189898671-d42eee71-1441-4a9a-a602-7eb24b7b901c.png)
 

(base) suat.coskun@sertinel06f01:~$ echo $PATH
/home/suat.coskun/anaconda2/bin:/home/suat.coskun/anaconda2/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
(base) suat.coskun@sertinel06f01:~$ echo $PYTHONPATH

(base) suat.coskun@sertinel06f01:~$ 





 and this is my paths;

**Comment by yumorishita** [comment]
You mean `./batch_LiCSBAS_ALOS.sh` worked and you got the result of ALOS time series?
According to the $PATH and $PYTHONPATH you showed, you did not successfully install LiCSBAS. In that terminal, LiCSBAS would not run.

**Comment by suatcoskun** [comment]
Yes i create this velocity map  with modify ./batch_LiCSBAS_ALOS.sh script and i am not faced any error message. 

![Screenshot from 2022-09-13 15-31-41](https://user-images.githubusercontent.com/36503613/189901806-3a1e12fa-2541-4e42-817c-348be38f67a8.png)

**Comment by yumorishita** [comment]
OK! Let me close this issue though I am not sure what fixed the problem.
