### ISSUE TITLE
Error in LiCSBASpatch_AIST_ALOS

### ISSUE THREAD

**Issue by yogen1992** [yumorishita/LiCSBASpatch_AIST_ALOS#3]
Dear Sir, while running the LiCSBAS for ALOS, I encountered the following error.
I am using the Ubuntu system. I also processed the data for LiCSBAS without any errors. However, while using ALOS products I encountered the error. I am adding the log file. Please help me.
[202310301058batch_LiCSBAS_ALOS_01_16.log](https://github.com/yumorishita/LiCSBASpatch_AIST_ALOS/files/13200424/202310301058batch_LiCSBAS_ALOS_01_16.log)

**Comment by yumorishita** [comment]
Please see https://github.com/yumorishita/LiCSBAS/issues/299.
