### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'baselines'

### ISSUE THREAD

**Issue by irmayolii** [yumorishita/LiCSBASpatch_AIST_ALOS#4]
Dear prof Morishita,
I try to run the script but it was error no such file or directory baseline

LiCSBAS01_get_geotiff_ALOS.py ver1.0.0 20220803 Y. Morishita
LiCSBAS01_get_geotiff_ALOS.py -f 445_0030_343

Frame ID is 445_0030_343

Download https://s3.abci.ai/palsar-insar-pds/P1INSAR/GUNW/445_0030_343/445_0030_343_GUNW.baselines as baselines
    ConnectionError for 445_0030_343_GUNW.baselines in 1th try
    ConnectionError for 445_0030_343_GUNW.baselines in 2th try
    ConnectionError for 445_0030_343_GUNW.baselines in 3th try
    Error while downloading from https://s3.abci.ai/palsar-insar-pds/P1INSAR/GUNW/445_0030_343/445_0030_343_GUNW.baselines
Download https://gsrt.digiarc.aist.go.jp/insarbrowser/doc/445_0030_343/network.png as network.png
    network.png, 159.41KB, 1s, 159.41KB/s
Download https://gsrt.digiarc.aist.go.jp/insarbrowser/doc/445_0030_343/products_list.txt as products_list.txt
    products_list.txt, 321.36KB, 1s, 321.36KB/s
Download https://gsrt.digiarc.aist.go.jp/insarbrowser/doc/445_0030_343/unwrap_rates_list.txt as unwrap_rates_list.txt
    unwrap_rates_list.txt, 5.11KB, 1s, 5.11KB/s

Traceback (most recent call last):
  File "/home/cws2-14/LiCSBAS2/LiCSBASpatch_AIST_ALOS/bin/LiCSBAS01_get_geotiff_ALOS.py", line 368, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/cws2-14/LiCSBAS2/LiCSBASpatch_AIST_ALOS/bin/LiCSBAS01_get_geotiff_ALOS.py", line 161, in main
    with open('baselines', 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'baselines'

[202408161508batch_LiCSBAS2_ALOS_01_16.log](https://github.com/user-attachments/files/16634694/202408161508batch_LiCSBAS2_ALOS_01_16.log)

**Comment by yumorishita** [comment]
The files are hosted on ABCI but it is under maintenance and not accessible by the end of this month. Please try after the maintenance.
https://abci.ai/en/about_abci/info.html

![image](https://github.com/user-attachments/assets/f8480b5e-f69f-4072-82aa-61b164f2cfc4)

**Comment by irmayolii** [comment]
Thank you for your response. I will check it after the maintenance.

**Comment by sakuya-izayoi-0518** [comment]
Dear Mr. Morishita,

I hope this message finds you well.

We are encountering the same error as mentioned previously. Based on the information available at https://abci.ai/en/about_abci/info.html, it does not appear that there is any specific issue.

We apologize for the inconvenience, but we would appreciate it if you could provide guidance on how to resolve this.

The full error log is as follows:
```

```
